find-mmc-bypartlabel: Allow more devices when finding partition
[find-mmc-bypartlabel] Allow more devices when finding partition. JB#63804

diff --git a/find-mmc-bypartlabel b/find-mmc-bypartlabel
--- a/find-mmc-bypartlabel
+++ b/find-mmc-bypartlabel
@@ -30,19 +30,29 @@ if [ ! -d /sys/class/block ]; then
 	exit 1
 fi
 
-while [ ! -d /sys/class/block/mmcblk[01]p* ] && [ ! -d /sys/class/block/sda ] ; do
-    echo "find-mmc-bypartlabel: Waiting for /sys/class/block/mmcblk[01]p*..." > /dev/kmsg
+check_block_devs()
+{
+    for p in /sys/class/block/mmcblk[01]p*/ /sys/class/block/sd[a-z]*/ ; do
+        if [ -d $p ]; then
+            return 0
+        fi
+    done
+    return 1
+}
+
+while ! check_block_devs ; do
+    echo "find-mmc-bypartlabel: Waiting for /sys/class/block/mmcblk[01]p* or /sys/class/block/sd[a-z]*..." > /dev/kmsg
     i=$(( ${i:-0} + 1 ))
     sleep 0.5
     if [ $i -eq 10 ]; then
-        echo "find-mmc-bypartlabel: Error: timeout waiting for /sys/class/block/mmcblk[01]p*" > /dev/kmsg
+        echo "find-mmc-bypartlabel: Error: timeout waiting for /sys/class/block/mmcblk[01]p* or /sys/class/block/sd[a-z]*" > /dev/kmsg
         exit 1
     fi
 done
 while [ ${i:-0} -le 50 ] ; do
-	for mmc_sysfs in /sys/class/block/mmcblk[01]p*/ /sys/class/block/sda*/; do
+	for mmc_sysfs in /sys/class/block/mmcblk[01]p*/ /sys/class/block/sd[a-z]*/; do
 		if grep -q -w PARTNAME="$1" "$mmc_sysfs"/uevent 2> /dev/null; then
-			FIMAGE_DEV_NAME=$(echo $mmc_sysfs | cut -d "/" -f 5)
+			FIMAGE_DEV_NAME=$(echo "$mmc_sysfs" | cut -d "/" -f 5)
 			echo "/dev/$FIMAGE_DEV_NAME"
 			exit 0
 		fi
